### 1. Get Linux
#FROM alpine:3.7
#FROM python:3.8.9-buster
#-alpine3.11
#FROM ubuntu:20.04
FROM ubuntu:20.04
#FROM centos:7
#FROM python:3.7-slim-stretch


# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME



# Install Python
# MAINTAINER fnndsc "dev@babymri.org"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y python3-pip python3-dev \
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip

ENTRYPOINT ["python3"]


# sudo apt-get update  && sudo apt-get install -y python3-pip python3-dev  && sudo cd /usr/local/bin  && sudo ln -s /usr/bin/python3 python  && sudo pip3 install --upgrade pip

#
#ENV FLASK_APP main.py
#ENV FLASK_RUN_HOST 0.0.0.0
#ENV FLASK_RUN_PORT 8080
#### Get Flask for the app
#RUN pip install --trusted-host pypi.python.org flask


EXPOSE 8080
WORKDIR /app
COPY requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
#ENV=LANG en_US.UTF-8
#ENV LANGUAGE en_US:en
#ENV LC_ALL en_US.UTF-8
CMD ['streamlit', 'run', 'main.py', '--server.port', '8080']










