### 1. Get Linux
#FROM alpine:3.7
#FROM python:3.8.9-buster
#-alpine3.11
#FROM ubuntu:20.04
#FROM ubuntu:18.04
FROM centos:7

# Install Java
RUN yum update -y \
&& yum install java-1.8.0-openjdk -y \
&& yum clean all \
&& rm -rf /var/cache/yum

# Set JAVA_HOME environment var
ENV JAVA_HOME="/usr/lib/jvm/jre-openjdk"

# Install Python
RUN yum install python3 -y \
&& pip3 install --upgrade pip setuptools wheel \
&& if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi \
&& if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi \
&& yum clean all \
&& rm -rf /var/cache/yum




#y

#RUN curl https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz -O -J -L && \
#    tar xzf Python-3.7.0.tgz -C /usr/src/ && \
#    /usr/src/Python-3.7.0/configure --enable-optimizations --prefix=/usr/bin/python3 && \
#    make altinstall && \
#    ln -s /usr/bin/python3/bin/python3.7 /usr/bin/python3.7 && \
#    rm Python-3.7.0.tgz

ENV FLASK_APP main.py
ENV FLASK_RUN_HOST 0.0.0.0
ENV FLASK_RUN_PORT 8080
### Get Flask for the app
RUN pip install --trusted-host pypi.python.org flask


#### OPTIONAL : 4. SET JAVA_HOME environment variable, uncomment the line below if you need it

ENV JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk"

####
#
#EXPOSE 81
#ADD test.py /
#CMD ["python", "test.py"]

#FROM python:3.7
EXPOSE 8080
WORKDIR /app
COPY requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt


COPY . .
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
CMD streamlit run main.py --server.port 8080










